include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - test/fixtures/flutter_app/**

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - directives_ordering
    - only_throw_errors
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - use_super_parameters
