packages:
  - packages/*
allowBuilds:
  esbuild: true
  node-pty: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@types/node@24.13.3'
  - '@tinyrack/docs@0.3.0 || 0.3.1'
  - '@tinyrack/ui@0.3.0'
